import "../tools/linux-test.flex";
fn lt_reject(qemu,app,firmware,temp,kind,message) {
    let bytes=h_read(app);let size=h_file_size;let ph=load64(bytes+32);
    if kind==0 {store64(bytes+ph+32,size+1);}else if kind==1 {store64(bytes+ph+16,0x100000);}else if kind==2 {store8(bytes+ph,3);}else if kind==3 {store64(bytes+24,0x8000000);}else {store64(bytes+ph+48,3);}
    let invalid=h_join(temp,"invalid.elf");h_save_bytes(invalid,bytes,size,384);qt_process=h_spawn(lh_args(qemu,invalid,firmware,temp),0,0);qt_until(message);
    lt_check(!h_has(h_out(qt_process),"FlexOS Linux ABI ready"),"invalid executable entered user mode");qt_stop();return 0;
}
fn main(argc,argv) {
    h_environment(argc,argv);h_assert(argc==3 || argc==4,"Usage: test-linux FLEX-COMPILER QEMU [FIRMWARE] (from repository root)");
    let compiler=h_real(load64(argv+8));let qemu=h_real(h_executable(load64(argv+16)));let firmware=0;if argc==4 {firmware=h_real(load64(argv+24));}let temp=h_temp();h_mkdir("build/linux");
    let hello=h_real("build/linux/hello.elf");let hash=h_sha(hello);let native=h_ok(h_args(hello,0,0,0,0,0));lt_check(h_equal(h_out(native),"Hello from an unchanged Linux binary!\n"),"native Linux hello failed");
    lt_open(qemu,hello,firmware,temp);qt_until("Hello from an unchanged Linux binary!");lt_done(0);lt_check(h_equal(hash,h_sha(hello)) && h_equal(hash,h_sha(h_join(temp,"app.elf"))),"Linux ELF was modified for FlexOS");
    let abi=h_real("build/linux/abi.elf");h_compile(compiler,"tests/linux/abi.flex",abi);h_save(h_join(temp,"welcome.txt"),"Welcome to FlexOS. This kernel and its boot code were generated by Flexscript.\nStorage is volatile RAM. Type help for commands.");
    native=h_wait(h_spawn(h_args(abi,0,0,0,0,0),"",temp));lt_check(h_status(native)==23 && h_has(h_out(native),"ABI PASS"),h_cat("ABI fixture failed on Linux: ",h_out(native)));
    lt_open(qemu,abi,firmware,temp);qt_until("ABI PASS");lt_done(23);
    let app=lt_compile(compiler,temp,"echo","fn main(){let p=alloc(16);syscall(1,1,\"INPUT READY\\n\",12,0,0,0);let i=0;while i<8{let n=syscall(0,0,p+i,8-i,0,0,0);if n<=0{return 90;}i=i+n;}syscall(1,1,\"ECHO \",5,0,0,0);syscall(1,1,p,8,0,0,0);return 0;}");
    lt_open(qemu,app,firmware,temp);qt_until("INPUT READY");h_trigger(qt_process,"flexos!\n");qt_until("ECHO flexos!");lt_done(0);
    let launch=h_args(h_real("build/run-linux"),qemu,app,firmware,0,0);let wrapped=h_wait(h_spawn(launch,"flexos!\n",0));lt_check(h_status(wrapped)==0 && h_has(h_out(wrapped),"ECHO flexos!"),"launcher did not forward stdin after UART setup");
    app=lt_compile(compiler,temp,"loop","fn main(){syscall(1,1,\"USER LOOP\\n\",10,0,0,0);while 1{}return 0;}");lt_open(qemu,app,firmware,temp);qt_until("USER LOOP");qt_pause(50);
    let regs=qt_execute("human-monitor-command","{\"command-line\":\"info registers\"}");lt_check(h_has(regs,"CPL=3") && h_has(regs,"CS64"),"Linux application did not execute in ring-3 long mode");qt_stop();
    app=lt_compile(compiler,temp,"kernel-read","fn main(){return load64(0x100000);}");lt_open(qemu,app,firmware,temp);qt_until("cpl=3");lt_check(h_has(h_out(qt_process),"Linux process fault vector=14"),"kernel memory fault was not from user mode");lt_done(139);
    app=lt_compile(compiler,temp,"readonly-write","fn main(){let p=alloc(4096);syscall(10,p,4096,1,0,0,0);store64(p,123);return 0;}");lt_open(qemu,app,firmware,temp);qt_until("cpl=3");lt_check(h_has(h_out(qt_process),"error=7"),"user write protection was not enforced by the CPU");lt_done(139);
    app=lt_compile(compiler,temp,"no-execute","fn main(){let p=alloc(4096);store8(p,195);return ffi_call(p,0,0,0,0,0,0);}");lt_open(qemu,app,firmware,temp);qt_until("cpl=3");lt_check(h_has(h_out(qt_process),"error=21"),"non-executable user memory was executable");lt_done(139);
    app=lt_compile(compiler,temp,"privileged","fn main(){let p=syscall(9,0,4096,7,34,-1,0);store8(p,250);store8(p+1,195);return ffi_call(p,0,0,0,0,0,0);}");lt_open(qemu,app,firmware,temp);qt_until("cpl=3");lt_check(h_has(h_out(qt_process),"Linux process fault vector=13"),"user mode could execute privileged CLI");lt_done(139);
    // An ordinary Linux C executable also runs unchanged, without a FlexOS shim.
    let c=h_join(temp,"hello.c");app=h_join(temp,"hello-c.elf");h_save(c,"static const char text[]=\"Hello from ordinary C!\\n\"; void _start(void){__asm__ volatile(\"syscall\"::\"a\"(1L),\"D\"(1L),\"S\"(text),\"d\"(sizeof(text)-1):\"rcx\",\"r11\",\"memory\");__asm__ volatile(\"syscall\"::\"a\"(60L),\"D\"(0L):\"rcx\",\"r11\",\"memory\");__builtin_unreachable();}\n");
    let args=h_args("cc","-nostdlib","-static","-no-pie","-fno-stack-protector",c);h_add(args,"-o");h_add(args,app);h_ok(args);native=h_ok(h_args(app,0,0,0,0,0));lt_check(h_equal(h_out(native),"Hello from ordinary C!\n"),"native Linux C executable failed");
    hash=h_sha(app);lt_open(qemu,app,firmware,temp);qt_until("Hello from ordinary C!");lt_done(0);lt_check(h_equal(hash,h_sha(h_join(temp,"app.elf"))),"C executable was modified for FlexOS");
    app=h_absolute("build/linux/libc.elf");h_ok(h_args("cc","-static","-no-pie","tests/linux/libc.c","-o",app));native=h_ok(h_args(app,0,0,0,0,0));lt_check(h_has(h_out(native),"LIBC PASS"),"static libc fixture failed on Linux");
    lt_open(qemu,app,firmware,temp);qt_until("LIBC PASS");lt_done(0);
    app=h_absolute("build/linux/libc32.elf");let args32=h_args("cc","-m32","-static","-no-pie","-Wl,-Ttext-segment=0x400000","tests/linux/libc.c");h_add(args32,"-o");h_add(args32,app);h_ok(args32);native=h_ok(h_args(app,0,0,0,0,0));lt_check(h_has(h_out(native),"LIBC PASS"),"static i386 libc fixture failed on Linux");lt_open(qemu,app,firmware,temp);qt_until("LIBC PASS");lt_done(0);
    let bits=0;while bits<2 {app=h_absolute(h_cat3("build/linux/shm",h_int(bits),".elf"));args32=h_args("cc","-static","-no-pie","tests/linux/shm.c","-o",app);if bits==1 {h_add(args32,"-m32");h_add(args32,"-Wl,-Ttext-segment=0x400000");}h_ok(args32);native=h_ok(h_args(app,0,0,0,0,0));lt_check(h_has(h_out(native),"SHM PASS"),"native Linux shared memory fixture failed");lt_open(qemu,app,firmware,temp);qt_until("SHM PASS");lt_done(0);bits=bits+1;}
    app=h_absolute("build/linux/devices.elf");h_compile(compiler,"tests/linux/devices.flex",app);lt_open(qemu,app,firmware,temp);qt_until("DEVICES READY");qt_capture(h_join(temp,"devices.ppm"));lt_check(qt_pixel(32,32)==0x6ee0c9,"Linux framebuffer mapping did not reach real VGA");
    qt_key_state("w",1);qt_pause(100);qt_key_state("w",0);qt_until("DEVICE PASS");lt_done(0);
    let root=h_join(temp,"rootfs");h_mkdir(root);h_mkdir(h_join(root,"data"));let bytes=h_zero(h_take(4),4);store8(bytes,65);store8(bytes+2,255);store8(bytes+3,66);h_save_bytes(h_join(root,"data/bytes.bin"),bytes,4,384);
    lh_rootfs=h_join(temp,"rootfs.tar");let tar=h_args("tar","--format=ustar","-cf",lh_rootfs,"-C",root);h_add(tar,".");h_ok(tar);lh_command="\"hello world\" \"\"";
    app=h_absolute("build/linux/rootfs.elf");h_compile(compiler,"tests/linux/rootfs.flex",app);lt_open(qemu,app,firmware,temp);qt_until("ROOTFS PASS");lt_done(0);
    bytes=h_read(lh_rootfs);let size=h_file_size;store8(bytes+148,load8(bytes+148)^1);h_save_bytes(lh_rootfs,bytes,size,384);qt_process=h_spawn(lh_args(qemu,app,firmware,temp),0,0);qt_until("invalid rootfs tar checksum");lt_check(!h_has(h_out(qt_process),"FlexOS Linux ABI ready"),"invalid rootfs entered user mode");qt_stop();lh_rootfs=0;lh_command=0;
    lt_reject(qemu,hello,firmware,temp,0,"invalid application file extent");lt_reject(qemu,hello,firmware,temp,1,"application segment outside supported address range");lt_reject(qemu,hello,firmware,temp,2,"dynamic linking is not supported yet");lt_reject(qemu,hello,firmware,temp,3,"application entry must be inside executable file bytes");lt_reject(qemu,hello,firmware,temp,4,"invalid application segment alignment");
    h_remove(temp);h_print(1,h_cat3("PASS: ",h_int(lt_checks)," Linux/FlexOS identical-ELF, syscall, ring-3, fault, UART and loader checks\n"));return 0;
}
